#!perl

use strict;
use warnings;

use App::FileTestUtils;

# AUTHORITY
# DATE
# DIST
# VERSION

App::FileTestUtils::do_script("dir_not_empty");

# ABSTRACT: Test that a directory is not empty
# PODNAME:

=head1 SYNOPSIS

On the command-line, you feed a filename as argument to the script and it will
exit 0 if the filename exists and is a non-empty directory:

 % dir-not-empty "foo" && echo "foo/ is not empty"

With grep mode (C<-g>), you pass one or more filenames in argument or stdin to
the script and it will print the non-empty directories (or those that are not,
if you specify C<-v> or C<--invert-match>).


=head1 DESCRIPTION

This is CLI for L<File::MoreUtil>'s L<dir_empty|File::MoreUtil/dir_not_empty>.


=head1 SEE ALSO

L<File::MoreUtil>

L<dir-empty>
