#!perl

# DATE
# VERSION

use strict;
use warnings;

use File::MoreUtil 'dir_has_dot_subdirs';

unless (@ARGV == 1) {
    die "Usage: dir-has-dot-subdirs <path>\n";
}

exit(dir_has_dot_subdirs($ARGV[0]) ? 0:1);

# ABSTRACT: Test that a directory has dot subdirectories
# PODNAME:

=head1 SYNOPSIS

On the command-line:

 % dir-has-dot-subdirs "foo" && echo "foo/ has dot subdirs"


=head1 DESCRIPTION

This is a simple CLI for L<File::MoreUtil>'s
L<dir_has_dot_subdirs|File::MoreUtil/dir_has_dot_subdirs>. It will exit 0 if
argument is a directory and has dot (a.k.a. hidden) subdirectories.


=head1 SEE ALSO

L<File::MoreUtil>

L<dir-has-subdirs>

L<dir-has-non-dot-subdirs>
