#!perl

use strict;
use warnings;

use App::FileTestUtils;

# AUTHORITY
# DATE
# DIST
# VERSION

App::FileTestUtils::do_script("dir_only_has_non_dot_subdirs");

# ABSTRACT: Test that a directory only has non-dot subdirectories
# PODNAME:

=head1 SYNOPSIS

On the command-line, you feed a filename as argument to the script and it will
exit 0 if the filename exists and is a directory that only has non-dot subdirs:

 % dir-only-has-non-dot-subdirs "foo" && echo "foo/ only has non-dot subdirs"

With grep mode (C<-g>), you pass one or more filenames in argument or stdin to
the script and it will print the directories that only have non-dot subdirs (or
those that are not, if you specify C<-v> or C<--invert-match>).

=head1 DESCRIPTION

This is CLI for L<File::MoreUtil>'s
L<dir_only_has_non_dot_subdirs|File::MoreUtil/dir_only_has_non_dot_subdirs>.


=head1 SEE ALSO

L<File::MoreUtil>

L<dir-has-non-dot-subdirs>
