#!perl

# DATE
# VERSION

use strict;
use warnings;

use File::MoreUtil 'dir_has_dot_files';

unless (@ARGV == 1) {
    die "Usage: dir-has-dot-files <path>\n";
}

exit(dir_has_dot_files($ARGV[0]) ? 0:1);

1;
# ABSTRACT: Test that a directory has dot files
# PODNAME:

=head1 SYNOPSIS

On the command-line:

 % dir-has-dot-files "foo" && echo "foo/ has dot files"


=head1 DESCRIPTION

This is a simple CLI for L<File::MoreUtil>'s
L<dir_has_dot_files|File::MoreUtils/dir_has_dot_files>. It will exit 0 if
argument is a directory and has plain, dot (a.k.a. hidden) files. A plain file
is a regular/non-special file. A symlink to a plain file counts as a plain file.
Non-plain files include named pipes, Unix sockets, and block/character special
files.


=head1 SEE ALSO

L<File::MoreUtil>

L<dir-has-files>

L<dir-has-non-dot-files>
