#!perl

# DATE
# VERSION

use strict;
use warnings;

use File::MoreUtil 'dir_has_non_dot_files';

unless (@ARGV == 1) {
    die "Usage: dir-has-non-dot-files <path>\n";
}

exit(dir_has_non_dot_files($ARGV[0]) ? 0:1);

# ABSTRACT: Test that a directory has non-dot files
# PODNAME:

=head1 SYNOPSIS

On the command-line:

 % dir-has-non-dot-files "foo" && echo "foo/ has non-dot files"


=head1 DESCRIPTION

This is a simple CLI for L<File::MoreUtil>'s
L<dir_has_non_dot_files|File::MoreUtils/dir_has_non_dot_files>. It will exit 0
if argument is a directory and has plain, non-dot (a.k.a. non-hidden) files. A
plain file is a regular/non-special file. A symlink to a plain file counts as a
plain file. Non-plain files include named pipes, Unix sockets, and
block/character special files.


=head1 SEE ALSO

L<File::MoreUtil>

L<dir-has-files>

L<dir-has-dot-files>
