#!perl

# DATE
# VERSION

use strict;
use warnings;

use File::MoreUtil 'dir_empty';

unless (@ARGV == 1) {
    die "Usage: dir-empty <path>\n";
}

exit(dir_empty($ARGV[0]) ? 0:1);

# ABSTRACT: Test that a directory is empty
# PODNAME:

=head1 SYNOPSIS

On the command-line:

 % dir-empty "foo" && echo "foo/ is empty"


=head1 DESCRIPTION

This is a simple CLI for L<File::MoreUtil>'s
L<dir_empty|File::MoreUtil/dir_empty>. It will exit 0 if argument is a
directory and is empty.


=head1 SEE ALSO

L<File::MoreUtil>
